const Colliders = {
    Forest : {

        // "x,y" : true  -> x and y are in pixels [convention for this project]
        // Marking coordinate of collision objects as true 

        [Utilities.asGridCords(13,12)] : true,
        [Utilities.asGridCords(14,12)] : true,
        [Utilities.asGridCords(15,12)] : true,
        [Utilities.asGridCords(16,12)] : true,

        //Trees Colliders
        [Utilities.asGridCords(11,13)] : true,
        [Utilities.asGridCords(10,13)] : true,
        [Utilities.asGridCords(31,2)] : true,
        [Utilities.asGridCords(32,2)] : true,
        [Utilities.asGridCords(31,1)] : true,
        [Utilities.asGridCords(34,3)] : true,
        [Utilities.asGridCords(35,3)] : true,

        //Grass Clumps
        [Utilities.asGridCords(33,7)] : true,
        [Utilities.asGridCords(33,8)] : true,
        [Utilities.asGridCords(33,9)] : true,
        [Utilities.asGridCords(34,7)] : true,
        [Utilities.asGridCords(35,7)] : true,
        [Utilities.asGridCords(36,7)] : true,
        [Utilities.asGridCords(37,7)] : true,
        [Utilities.asGridCords(14,0)] : true,
        [Utilities.asGridCords(14,1)] : true,
        [Utilities.asGridCords(14,2)] : true,
        [Utilities.asGridCords(14,3)] : true,
        [Utilities.asGridCords(14,4)] : true,

        //Elevated ground Borders

        //#1
        [Utilities.asGridCords(7,6)] : true,
        [Utilities.asGridCords(8,6)] : true,
        [Utilities.asGridCords(9,6)] : true,
        [Utilities.asGridCords(10,6)] : true,
        [Utilities.asGridCords(11,6)] : true,
        [Utilities.asGridCords(12,6)] : true,
        [Utilities.asGridCords(13,6)] : true,
        [Utilities.asGridCords(14,6)] : true,
        [Utilities.asGridCords(15,6)] : true,
        [Utilities.asGridCords(16,6)] : true,
        [Utilities.asGridCords(17,6)] : true,
        [Utilities.asGridCords(18,6)] : true,
        [Utilities.asGridCords(19,6)] : true,
        [Utilities.asGridCords(20,6)] : true,
        [Utilities.asGridCords(21,6)] : true,

        [Utilities.asGridCords(15,5)] : true,
        [Utilities.asGridCords(16,5)] : true,
        [Utilities.asGridCords(17,5)] : true,
        [Utilities.asGridCords(18,5)] : true,
        [Utilities.asGridCords(19,5)] : true,
        [Utilities.asGridCords(20,5)] : true,
        [Utilities.asGridCords(21,5)] : true,
        [Utilities.asGridCords(22,5)] : true,
        [Utilities.asGridCords(22,6)] : true,
        [Utilities.asGridCords(22,7)] : true,
        [Utilities.asGridCords(22,8)] : true,
        [Utilities.asGridCords(22,9)] : true,

        //Border
        [Utilities.asGridCords(38,6)] : true,
        [Utilities.asGridCords(38,5)] : true,
        [Utilities.asGridCords(38,4)] : true,
        [Utilities.asGridCords(37,3)] : true,
        [Utilities.asGridCords(37,2)] : true,
        [Utilities.asGridCords(36,2)] : true,
        [Utilities.asGridCords(35,2)] : true,
        [Utilities.asGridCords(34,2)] : true,
        [Utilities.asGridCords(33,2)] : true,
        [Utilities.asGridCords(32,2)] : true,
        [Utilities.asGridCords(32,1)] : true,
        [Utilities.asGridCords(31,1)] : true,
        [Utilities.asGridCords(30,1)] : true,

        [Utilities.asGridCords(29,0)] : true,
        [Utilities.asGridCords(28,-1)] : true,
        [Utilities.asGridCords(27,-1)] : true,
        [Utilities.asGridCords(26,-1)] : true,
        [Utilities.asGridCords(25,-1)] : true,
        [Utilities.asGridCords(24,-1)] : true,
        [Utilities.asGridCords(23,-1)] : true,
        [Utilities.asGridCords(22,-1)] : true,
        [Utilities.asGridCords(21,-1)] : true,
        [Utilities.asGridCords(20,-1)] : true,
        [Utilities.asGridCords(19,-1)] : true,
        [Utilities.asGridCords(18,-1)] : true,
        [Utilities.asGridCords(17,-1)] : true,
        [Utilities.asGridCords(16,-1)] : true,
        [Utilities.asGridCords(15,-1)] : true,


        // #2
        [Utilities.asGridCords(22,11)] : true,
        [Utilities.asGridCords(23,11)] : true,
        [Utilities.asGridCords(24,11)] : true,
        [Utilities.asGridCords(25,11)] : true,
        [Utilities.asGridCords(29,11)] : true,
        [Utilities.asGridCords(30,11)] : true,
        [Utilities.asGridCords(31,11)] : true,
        [Utilities.asGridCords(32,11)] : true,
        [Utilities.asGridCords(33,11)] : true,
        [Utilities.asGridCords(34,11)] : true,
        [Utilities.asGridCords(35,11)] : true,

        [Utilities.asGridCords(22,10)] : true,
        [Utilities.asGridCords(23,10)] : true,
        [Utilities.asGridCords(24,10)] : true,
        [Utilities.asGridCords(25,10)] : true,
        [Utilities.asGridCords(29,10)] : true,
        [Utilities.asGridCords(30,10)] : true,
        [Utilities.asGridCords(31,10)] : true,
        [Utilities.asGridCords(32,10)] : true,
        [Utilities.asGridCords(33,10)] : true,
        [Utilities.asGridCords(34,10)] : true,
        [Utilities.asGridCords(35,10)] : true,

        //Fence collision
        [Utilities.asGridCords(6,6)] : true,
        [Utilities.asGridCords(6,7)] : true,
        [Utilities.asGridCords(6,8)] : true,
        [Utilities.asGridCords(6,9)] : true,
        [Utilities.asGridCords(6,10)] : true,
        [Utilities.asGridCords(6,11)] : true,
        [Utilities.asGridCords(6,12)] : true,
        [Utilities.asGridCords(6,13)] : true,
        [Utilities.asGridCords(6,14)] : true,
        [Utilities.asGridCords(6,15)] : true,
        [Utilities.asGridCords(6,16)] : true,
        [Utilities.asGridCords(6,17)] : true,
        [Utilities.asGridCords(6,18)] : true,
        [Utilities.asGridCords(6,19)] : true,
        [Utilities.asGridCords(6,20)] : true,
        [Utilities.asGridCords(7,20)] : true,
        [Utilities.asGridCords(8,20)] : true,
        [Utilities.asGridCords(8,21)] : true,
        [Utilities.asGridCords(8,22)] : true,
        [Utilities.asGridCords(8,23)] : true,
        [Utilities.asGridCords(9,23)] : true,
        [Utilities.asGridCords(10,23)] : true,
        [Utilities.asGridCords(11,23)] : true,
        [Utilities.asGridCords(12,23)] : true,
        [Utilities.asGridCords(16,23)] : true,
        [Utilities.asGridCords(17,23)] : true,
        [Utilities.asGridCords(18,23)] : true,
        [Utilities.asGridCords(19,23)] : true,
        [Utilities.asGridCords(20,23)] : true,
        [Utilities.asGridCords(21,23)] : true,
        [Utilities.asGridCords(22,23)] : true,
        [Utilities.asGridCords(23,23)] : true,
        [Utilities.asGridCords(24,23)] : true,
        [Utilities.asGridCords(25,23)] : true,
        [Utilities.asGridCords(26,23)] : true,
        [Utilities.asGridCords(27,23)] : true,
        [Utilities.asGridCords(28,24)] : true,
        [Utilities.asGridCords(28,25)] : true,
        [Utilities.asGridCords(28,26)] : true,
        [Utilities.asGridCords(28,27)] : true,
        [Utilities.asGridCords(29,27)] : true,
        [Utilities.asGridCords(30,27)] : true,
        [Utilities.asGridCords(31,27)] : true,
        [Utilities.asGridCords(31,26)] : true,
        [Utilities.asGridCords(31,25)] : true,
        [Utilities.asGridCords(31,24)] : true,
        [Utilities.asGridCords(31,23)] : true,
        [Utilities.asGridCords(32,23)] : true,
        [Utilities.asGridCords(33,23)] : true,
        [Utilities.asGridCords(34,23)] : true,
        [Utilities.asGridCords(35,23)] : true,
        [Utilities.asGridCords(35,22)] : true,
        [Utilities.asGridCords(36,22)] : true,
        [Utilities.asGridCords(36,21)] : true,
        [Utilities.asGridCords(36,20)] : true,
        [Utilities.asGridCords(36,19)] : true,
        [Utilities.asGridCords(36,18)] : true,
        [Utilities.asGridCords(36,17)] : true,
        [Utilities.asGridCords(36,16)] : true,
        [Utilities.asGridCords(36,15)] : true,
        [Utilities.asGridCords(36,14)] : true,
        [Utilities.asGridCords(36,13)] : true,
        [Utilities.asGridCords(36,12)] : true,

        //Island Boundries

        // #rightPart
        [Utilities.asGridCords(24,37)] : true,
        [Utilities.asGridCords(24,36)] : true,
        [Utilities.asGridCords(24,35)] : true,
        [Utilities.asGridCords(24,34)] : true,
        [Utilities.asGridCords(24,33)] : true,
        [Utilities.asGridCords(24,32)] : true,
        [Utilities.asGridCords(24,31)] : true,
        [Utilities.asGridCords(23,31)] : true,
        [Utilities.asGridCords(22,31)] : true,
        [Utilities.asGridCords(21,31)] : true,
        [Utilities.asGridCords(21,30)] : true,
        [Utilities.asGridCords(21,29)] : true,
        [Utilities.asGridCords(21,28)] : true,
        [Utilities.asGridCords(20,28)] : true,
        [Utilities.asGridCords(19,28)] : true,
        [Utilities.asGridCords(18,28)] : true,
        [Utilities.asGridCords(17,28)] : true,
        [Utilities.asGridCords(16,28)] : true,
        [Utilities.asGridCords(16,27)] : true,
        [Utilities.asGridCords(16,26)] : true,
        [Utilities.asGridCords(16,25)] : true,
        [Utilities.asGridCords(16,24)] : true,

        // #leftPart
        [Utilities.asGridCords(12,24)] : true,
        [Utilities.asGridCords(12,25)] : true,
        [Utilities.asGridCords(12,26)] : true,
        [Utilities.asGridCords(12,27)] : true,
        [Utilities.asGridCords(12,28)] : true,
        [Utilities.asGridCords(11,28)] : true,
        [Utilities.asGridCords(10,28)] : true,
        [Utilities.asGridCords(9,28)] : true,
        [Utilities.asGridCords(9,29)] : true,
        [Utilities.asGridCords(9,30)] : true,
        [Utilities.asGridCords(9,31)] : true,
        [Utilities.asGridCords(8,31)] : true,
        [Utilities.asGridCords(7,31)] : true,
        [Utilities.asGridCords(7,32)] : true,
        [Utilities.asGridCords(7,33)] : true,
        [Utilities.asGridCords(7,34)] : true,
        [Utilities.asGridCords(7,35)] : true,
        [Utilities.asGridCords(7,36)] : true,
        [Utilities.asGridCords(7,37)] : true,

        // Lower Border
        [Utilities.asGridCords(7,38)] : true,
        [Utilities.asGridCords(8,38)] : true,
        [Utilities.asGridCords(9,38)] : true,
        [Utilities.asGridCords(10,38)] : true,
        [Utilities.asGridCords(11,38)] : true,
        [Utilities.asGridCords(12,38)] : true,
        [Utilities.asGridCords(13,38)] : true,
        [Utilities.asGridCords(14,38)] : true,
        [Utilities.asGridCords(15,38)] : true,
        [Utilities.asGridCords(16,38)] : true,
        [Utilities.asGridCords(17,38)] : true,
        [Utilities.asGridCords(18,38)] : true,
        [Utilities.asGridCords(19,38)] : true,
        [Utilities.asGridCords(20,38)] : true,
        [Utilities.asGridCords(21,38)] : true,
        [Utilities.asGridCords(22,38)] : true,
        [Utilities.asGridCords(23,38)] : true,

    }
    
}